# Generated by Django 2.0.3 on 2018-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuário', models.CharField(max_length=30)),
                ('Senha', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Nome', models.CharField(max_length=30)),
                ('Endereço', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Celular', models.CharField(max_length=30)),
                ('bio', models.TextField()),
            ],
        ),
    ]
