# Generated by Django 2.0.3 on 2018-03-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Endereço',
            new_name='Endereco',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Usuário',
            new_name='Usuario',
        ),
    ]
